# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Report&CleanDuplicates.py
# Created on: 2019-02-14 20:46:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Report&CleanDuplicates <Target_Shapefile> <Cleaned_Shapefile> 
# Description: 
# Identifies and reports on duplicates of geometry and record numbers, and then deletes the duplicates.
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments
Target_Shapefile = arcpy.GetParameterAsText(0)
if Target_Shapefile == '#' or not Target_Shapefile:
    Target_Shapefile = "D:\\Programming\\Data\\Inputs\\Network.shp" # provide a default value if unspecified

Cleaned_Shapefile = arcpy.GetParameterAsText(1)
if Cleaned_Shapefile == '#' or not Cleaned_Shapefile:
    Cleaned_Shapefile = "D:\\Programming\\Data\\Inputs\\Network.shp" # provide a default value if unspecified

# Local variables:
Identical_Record_Numbers = "D:\\Programming\\Data\\Inputs\\IdenticalRecNos.dbf"
Identical_Shapes = "D:\\Programming\\Data\\Inputs\\IdenticalShape.dbf"

# Process: Find Identical RecNos
arcpy.FindIdentical_management(Target_Shapefile, Identical_Record_Numbers, "RECNO", "0.5 Meters", "0", "ONLY_DUPLICATES")

# Process: Delete Identical Shapes & RecNos
arcpy.DeleteIdentical_management(Target_Shapefile, "Shape;RECNO", "0.5 Meters", "0")

# Process: Find Identical Shapes
arcpy.FindIdentical_management(Target_Shapefile, Identical_Shapes, "Shape", "0.5 Meters", "0", "ONLY_DUPLICATES")

